### PR TITLE
Implemented getting channel by name in HTTP unicasts, i.e. GET /byname/c...

### PR DESCRIPTION
**Pull request by lobodpav**
Implemented getting channel by name in HTTP unicasts, i.e. GET /byname/channelname

### CODE REVIEW

**Comment by braice** [comment]
Thanks !

**Comment by lobodpav** [comment]
Glad to help :)
There is just one issue I found with the 'space' to 'dash' replacement. If you have a channel named `CT D / CT Art`, then the name you have to type is a bit complex - `CT-D-/-CT-Art`. I have not found a better solution though :(

**Comment by braice** [comment]
Maybe you can escape spaces with the usual http notation %20
http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by lobodpav** [comment]
Yes, but this would not eliminate long names in URLs. Was thinking of a possibility to allow users to assign aliases to channels. But I'm not sure how to achieve it in your product.
Or maybe even better, by typing URL:port where the app listens, it could display a page witl links to all channels are available.

**Comment by braice** [comment]
Hello

2015-03-01 6:51 GMT+01:00 Pavel Lobodinský <notifications@github.com>:

> Yes, but this would not eliminate long names in URLs. Was thinking of a
> possibility to allow users to assign aliases to channels. But I'm not sure
> how to achieve it in your product.
>

In this case, you can specify the name in the conf and it's short enough



> Or maybe even better, by typing URL:port where the app listens, it could
> display a page witl links to all channels are available.
>
> —
>


It should work in the latest version

**Comment by lobodpav** [comment]
Didn't know that. Will take a look on it. Thanks!

**Pull request merged**
