### PR TITLE
T2-MI (over DVB) input support with demux

### PR DESCRIPTION
**Pull request by anphsw**
Fixed normal dvb packet processing regression.
Now fully tested and ready.

### CODE REVIEW

**Comment by anphsw** [comment]
This is patch to support T2-MI TPs in software (your card need to support modulation of such TPs, but many TPs using standard DVB-S or DVB-S2 QPSK/8PSK).
Now supported selection of any PLP from any PID.
example config:
t2mi_pid=4096
t2mi_plp=0

Out of sync recovery - many errors can cause out of sync: low SNR, radio interference on downlink and uplink sides, buggy modulator software, proprietary (non-TS) frame insertions.
Recovery done by flushing whole buffer and searching for the beginning of next frame, so in case of frequent errors you must set buffer as low as possible (minimal value = 20) to avoid video artefacts.

T2-MI TPs list:
http://enosat.euweb.cz/t2mi.htm

Note that "multistream" is not "T2-MI" and may (or may not) use ACM/VCM, so your card must support it.

**Comment by anphsw** [comment]
I want to write support for multi-plp, but there is a problem with autoconfiguration:
Each PLP have its own PAT with diffirent versions, so if I want to run autoconfigure on whole demuxed stream, autoconfiguradion running in endless loop forcing SDT update.
Is anybody interested (and/or) can help me? :)

**Comment by braice** [comment]
Hi

Quite different from a normal stream.

I don't see an easy way through that, but I am not super familiar with t2
mi.

Do you have a nice documentation to point me to ?

**Comment by anphsw** [comment]
Documetation of T2-MI is here: http://www.etsi.org/deliver/etsi_ts/102700_102799/102773/01.01.01_60/ts_102773v010101p.pdf
But originally reciever is not intended to work with all PLP, instead it must select one, and work with it.
PLP encapsulates standard TS traffic, there is no diffirence between recepting demuxed single PLP and DVB.
That is, imagine multple DVB TPs which than dumped to single file. Ordinary TS packets fine, but PAT from several streams have same pid.
Possibly workaround is duplicate incoming DVB traffic, and run several mumudvb processes on it concurrently, but i dont know how to do it (maybe dvbloopback?)
Other way is to append PLP number to each TS packet, and process each PAT independent from other.

**Comment by m0yellow** [comment]
how does this work on the driver level?
could you subscribe to only one PLP per process/thread, and the the other on another process without negative performance effect?

**Comment by anphsw** [comment]
There is no driver level for now. And if we want to support all dvb cards, we must not modify driver level.
I dont think that dvbloopback, or any driver modification is proper way, but it's possible.

At least we can output traffic from one mumudvb process via pipe and attach another mumudvb to that pipe as input. But it's better to deal with multiple pat tables in one process.

**Comment by anphsw** [comment]
I've added some t2-mi releated features if resulting streams is encrypted: its BISS static keys, and  exclusion scrambled streams from playlist (if you don't have keys).

**Comment by anphsw** [comment]
It's ready for merge now, plus I fixed some errors in original code.

**Comment by braice** [comment]
Ok, I'll look into it

2017-03-23 4:55 GMT-04:00 anphsw <notifications@github.com>:

**Comment by braice** [comment]
Hello

As an improvement, can you try to move the t2-mi code as much as you can
outside of mumudvb.c ?

Will help lisibility of the main file

Thank you

Brice


2017-03-25 17:23 GMT-04:00 Brice Dubost <braice@braice.net>:

**Comment by anphsw** [comment]
Ok, I'll rearrange code and open next pull request when it's ready.

**Pull request merged**
