### PR TITLE
Fix setting voltage to OFF instead of 13v after sending JESS/Unicable…

### PR DESCRIPTION
**Pull request by gredek**
Had some strange behavior not able to tune on second system with S8 tuner card on Unicable Inverto MSW setup. Fixed it with setting the voltage off after send msg instead of leaving it on low voltage (13v). That fixed the issue.

### CODE REVIEW

**Comment by braice** [comment]
Hello
Can you document your new switch type in the doc/README_CONF.txt ?

Then we will have everything to include this change, I'll take care of updating the website.

Brice

**Comment by gredek** [comment]
Hi Brice,

I thought that was already done in my commit?

Greets

**Comment by braice** [comment]
maybe you forgot to add it

File Changes

   - *M* src/tune.c
   <https://github.com/braice/MuMuDVB/pull/222/files#diff-0> (16)

**Comment by gredek** [comment]
When I look to the commits on your repository i see

https://github.com/braice/MuMuDVB/commit/8a5862dd8503c8715098e1e7a51bef2f19e65084

or am I missing something here?

**Comment by braice** [comment]
Yes you are right, it was included in a previous commit

**Pull request merged**
