### PR TITLE
Fix pin_no/pin_number typo

### PR DESCRIPTION
**Pull request by freddy36**
Fix regresion (Build failes) introduced by #253

### CODE REVIEW

**Comment by freddy36** [comment]
@KlausReinhard please review

**Comment by KlausReinhard** [comment]
correct, mixed-up config-phrase and variable.

Also, please delete line 881 in tune.c since this pin_no-parameter is not used in do_diseqc function anymore.

thx, klaus

**Review by KlausReinhard — APPROVED** [review]
correct, mixed-up config phrase and variable

also, please delete line 881 since the parameter "pin_no" is not passed to function do_diseqc anymore

**Review by KlausReinhard — APPROVED** [review]
see previous comment

**Comment by braice** [comment]
Thank you !

**Pull request merged**
