### PR TITLE
Add support for streaming EMM PIDs

### LINKED ISSUE #183: Add support for EMM pid streaming
Hello,

currently MuMuDVB only sends the ECM pids for scrambled channels (Thank you @joeusercz #95).
The EMM pids (needed for card updates, etc.) are not sent. While the ECM pids are specified in the PMT, the EMM pids are specified in the Conditional Access Table (table id 1). I had a quick look at the code but it seems like the CAT is not parsed at all. Did I miss something? Would have expected that the EMM updates must be send to the (hardware) CAM too. 

@braice You got any hints for me where I should start to implement CAT parsing?

### PR DESCRIPTION
**Pull request by freddy36**
fixes #183 

A review would be appreciated

### CODE REVIEW

**Comment by braice** [comment]
Hello

Thank you for the patch, I'll review and merge early next week.

Brice

**Comment by braice** [comment]
Hello

Where is this file autoconf_cat.c ???

It is mentionned in the makefile but not present



Brice

**Comment by freddy36** [comment]
sorry, forgot that one ;)
just added it

**Comment by braice** [comment]
Hello

I have two questions about the code, first why is there 
//We also force a re read of the SDT
 +        auto_p->sdt_version=-1;

In autoconf_cat ?
It looks like a copy paste issue or did I miss something ?


Also why do you need to force PMT re reading when the cat is updated ? (at the end of autoconf CAT)

Thank you

brice

**Comment by freddy36** [comment]
The SDT contains the ECM pid mapping. I'm aware of at least one broken CAS implementation which won't increment the SDT version if it makes changes to it. As CAT updates are usually a rare event and usually is incorporated by a SDT update I decided to force refresh it as a workaround for broken CAS systems. In general it shouldn't be needed. Should I remove it?

The PMT update is needed as it actually adds the PIDs to the stream. If the PMT update is handled before the CAT was parsed the EMM pids won't be added. To avoid this race condition I added the PMT refresh.

**Pull request merged**
